name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Build Annotated Bibliography
        run: nix build .#annotatedBibliography

      - name: Get current date and build number
        id: date_version
        run: |
          DATE=$(date +'%Y.%-m.%-d')
          LAST_TAG=$(git tag --sort=-creatordate | grep "^v${DATE}" | head -n 1)
          if [[ -z "$LAST_TAG" ]]; then
            BUILD_NUMBER=0
          else
            BUILD_NUMBER=$(( $(echo "$LAST_TAG" | grep -oE '+$') + 1 ))
          fi
          echo "tag=v${DATE}.${BUILD_NUMBER}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date_version.outputs.tag }}
          release_name: ${{ steps.date_version.outputs.tag }}
          body: ""
          draft: false
          prerelease: false

      - name: Upload Annotated Bibliography to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./result/share/annotated-bibliography/main.pdf
          asset_name: annotated-bibliography.pdf
          asset_content_type: application/octet-stream
